# Generated by Django 4.2.7 on 2023-11-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoreDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'MoreDetail',
            },
        ),
    ]
